language: ruby
sudo: false
cache: bundler
bundler_args: "--deployment --jobs=3 --retry=10"
addons:
  postgresql: '9.3'
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- cp config/secrets.yml.template config/secrets.yml
script:
- bundle exec rake db:create db:migrate
- bundle exec rspec
