language: ruby
services:
  - postgresql
env:
  - RAILS_ENV=test
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rails db:setup
  - bundle exec rspec
