default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: it61_development

test:
  <<: *default
  database: it61_test

production:
  <<: *default
  url: <%= ENV['POSTGRESQL_URL'] %>
  database: it61_production
