default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default
  github_callback_url: http://0.0.0.0:3000/oauth/callback?provider=github
  github_key: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_CLIENT_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_CLIENT_SECRET"] %>
  google_key: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>


test:
  <<: *default
  github_key: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_CLIENT_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_CLIENT_SECRET"] %>
  google_key: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

staging:
  <<: *default

production:
  <<: *default
  github_callback_url: <%= ENV["GITHUB_CALLBACK_URL"] %>
  github_key: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_CLIENT_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_CLIENT_SECRET"] %>
  google_key: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
