default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_callback_url: <%= ENV["GITHUB_CALLBACK_URL"] %>
  github_key: <%= ENV["GITHUB_KEY"] %>
  github_secret: <%= ENV["GITHUB_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  google_key: <%= ENV["GOOGLE_KEY"] %>
  google_secret: <%= ENV["GOOGLE_SECRET"] %>
  vkontakte_key: <%= ENV["VK_KEY"] %>
  vkontakte_secret: <%= ENV["VK_SECRET"] %>

development:
  <<: *default
  secret_key_base: 6bb19d4c5dd650e9d7935d855bcb41b0c8428aa9697d51ea3df11e13d656f32fc11c31c23784c526f44ba64eb43c44b0cf1544a98847735191d8cf6c697b5146

test:
  <<: *default
  secret_key_base: 7faf58b28792800a1aa1166d71f99bdc0f9eb41bf51f8af4e34e1b5ada59fca1397cb8c532bcf198a9a3c16a999a87f7bb8d1c6774fcd78f4ebb21e6cb7d8143

staging:
  <<: *default

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
