default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_callback_url: <%= ENV["GITHUB_CALLBACK_URL"] %>
  github_key: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_CLIENT_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_CLIENT_SECRET"] %>
  google_key: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  vkontakte_key: <%= ENV["VK_CLIENT_ID"] %>
  vkontakte_secret: <%= ENV["VK_CLIENT_SECRET"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
