default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default
  sorcery_github_callback_url: http://0.0.0.0:3000/oauth/callback?provider=github
  sorcery_github_key: <%= ENV["GITHUB_CLIENT_ID"] %>
  sorcery_github_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>


test:
  <<: *default
  sorcery_github_key: <%= ENV["GITHUB_CLIENT_ID"] %>
  sorcery_github_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>

staging:
  <<: *default

production:
  <<: *default
  sorcery_github_callback_url: <%= ENV["GITHUB_CALLBACK_URL"] %>
  sorcery_github_key: <%= ENV["GITHUB_CLIENT_ID"] %>
  sorcery_github_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
